name: Auto Generate M3U

on:
  schedule:
    - cron: "0 * * * *"   # Her saat başı
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri kur
        run: |
          pip install requests urllib3

      - name: M3U oluştur
        run: |
          python main.py

      - name: Çıktıyı repoya kaydet
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add DeaTHlesS-Androtv.m3u
          git commit -m "Auto update M3U" || echo "Değişiklik yok"
          git push
